In [19]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
import chromedriver_autoinstaller
import csv
import time

In [20]:
#INSTALL BROWSER SUCH CHROME OR EDGE
chromedriver_autoinstaller.install()

#USE THE INSTALLED BROWSER FOR SELENIUM
browser = webdriver.Chrome()

In [21]:
data = []

for index in range (1,5):
    browser.get(f'https://www.tokopedia.com/search?navsource=home&page={index}&q=baju%20lebaran%20pria%20wanita&source=universe&srp_component_id=02.02.01.01&st=product')
    time.sleep(50)
    soup = BeautifulSoup(browser.page_source,"lxml")
    rows = soup.find_all('div', class_='css-974ipl')

In [26]:
    for row in rows:
        Product_Name = row.find(class_='prd_link-product-name css-3um8ox')
        if Product_Name:
            Product_Name = Product_Name.text
            
        Sold = row.find(class_='prd_label-integrity css-1duhs3e')
        if Sold:
            Sold = Sold.text
            
        Rating = row.find(class_='prd_rating-average-text css-t70v7i')
        if Rating:
            Rating = Rating.text
            
        Discount = row.find(class_='prd_badge-product-discount css-1qtulwh')
        if Discount:
            Discount = Discount.text
        
        Cashback = row.find(class_='prd_label-product-price css-tolj34')
        if Cashback:
            Cashback = Cashback.text
        
        Price = row.find(class_='prd_link-product-price css-1ksb19c')
        if Price:
            Price = Price.text
        
        Seller_Loct = row.find(class_='prd_link-shop-loc css-1kdc32b flip')
        if Seller_Loct:
            Seller_Loct = Seller_Loct.text
            
        
            
        #Nama_Toko = row.find(class_='prd_link-shop-name css-1kdc32b flip').text
        #Lokasi_Penjual = row.find(class_='prd_link-shop-loc css-1kdc32b flip').text
        
        
        df = {
            'Product Name': Product_Name,
            'Terjual': Sold,
            'Rating': Rating,
            'Dapatkan Diskon!': Discount,
            'Dapatkan Cashback': Cashback,
            'Harga Sekarang!': Price,
            'Lokasi_Penjual': Seller_Loct
            }
        data.append(df)

In [32]:
df = pd.DataFrame(data)

In [33]:
df

,Product Name,Terjual,Rating,Dapatkan Diskon!,Dapatkan Cashback,Harga Sekarang!,Lokasi_Penjual
0,SAMARA DRESS 3TONE (SILVER ALMOND KHAKIS) / GA...,Terjual 4,None,None,None,Rp 295.000,None
1,DAYU ALMOND / DRESS MUSLIM WANITA / GAMIS MUSL...,Terjual 12,5.0,None,None,Rp 285.000,None
2,KYANA ALMOND KHAKIS / DRESS MUSLIM WANITA / GA...,Terjual 5,5.0,None,None,Rp 295.000,None
3,Koko Pria Lengan Panjang Arra Series Salman Pr...,None,None,None,None,Rp159.000,Kab. Bandung Barat
4,Kemeja Koko Kurta Pria Lengan Pendek Baju Koko...,Terjual 18,4.7,None,Diskon 3%,Rp150.000,Bandung
...,...,...,...,...,...,...,...
161,Gamis Wanita Polos Crinkle/ Gamis Lebaran terb...,None,None,None,None,Rp91.120,Bandung
162,Gamis Brukat Hitam Wanita/Baju Muslim Umroh/Ga...,Terjual 16,5.0,None,None,Rp165.200,Jakarta Utara
163,Baju Gamis Putih/Busana Muslim Lebaran Haji/Ba...,Terjual 500+,5.0,74%,None,Rp196.110,Jakarta Utara
164,Gamis Brukat Hitam Wanita/Baju Muslim Umroh/Ga...,Terjual 18,4.9,None,None,Rp191.400,Jakarta Utara
165,Baju Gamis Terbaru 2023 Lebaran Wanita Kekinia...,Terjual 100+,4.8,None,Diskon Bundling,Rp112.000,Kab. Pekalongan

In [34]:
import pandas as pd

# Assuming you have a DataFrame named 'df' with columns 'Title', 'Price', and 'Rating'

# Save the DataFrame to a CSV file
df.to_csv('Tokopedia_Baju Lebaran Pria Wanita.csv', index=False)